# Copyright 2019-Present Sonatype Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  schedule:
    # schedule weekly tests, since dependencies are not intended to be pinned
    # this means: at 23:42 on Fridays
    - cron: '42 23 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPORTS_DIR: CI_reports
  PYTHON_VERSION_DEFAULT: "3.9"
  POETRY_VERSION: "1.8.1"
  TESTS_REPORTS_ARTIFACT: tests-reports

jobs:
  coding-standards:
    name: Linting & Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: 'x64'

      - name: Install poetry
        # see https://github.com/marketplace/actions/setup-poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tox
        run: poetry run tox run -e flake8 -s false

  static-code-analysis:
    name: StaticCodingAnalysis (py${{ matrix.python-version}} ${{ matrix.toxenv-factors }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - # test with the latest dependencies
            os: ubuntu-latest
            python-version: '3.9'
            toxenv-factors: '-locked'
          - # test with the lowest dependencies
            os: ubuntu-latest
            python-version: '3.6'
            toxenv-factors: '-lowest'
    steps:
      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install poetry
        # see https://github.com/marketplace/actions/setup-poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tox
        run: poetry run tox run -e mypy${{ matrix.toxenv-factors }} -s false

  build-and-test:
    name: Test (${{ matrix.os }} py${{ matrix.python-version }} ${{ matrix.toxenv-factors }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      REPORTS_ARTIFACT: tests-reports
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-13' ]
        python-version:
          - "3.9" # highest supported
          - "3.8"
          - "3.7"
          - "3.6" # lowest supported
        toxenv-factors:
          - '-locked'
          - '-lowest'
    steps:
      - name: Disabled Git auto EOL CRLF transforms
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        # see https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir ${{ env.REPORTS_DIR }}

      - name: Setup Python Environment
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Validate Python Environment
        shell: python
        run: |
          import sys
          print('Python %s on %s in %s' % (sys.version, sys.platform, sys.getdefaultencoding()))

      - name: Install poetry
        # see https://github.com/marketplace/actions/setup-poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: poetry install --no-root

      - name: Ensure build successful
        run: poetry build

      - name: Run tox
        run: poetry run tox run -e py${{ matrix.toxenv-factors }} -s false

      - name: Generate coverage reports
        if: ${{ failure() || success() }}
        shell: bash
        run: |
          set -eux
          poetry run coverage report -m
          poetry run coverage xml -o '${{ env.REPORTS_DIR }}/coverage/${{ matrix.os }}_py${{ matrix.python-version }}_${{ matrix.toxenv-factors }}.cobertura.xml'

      - name: Artifact reports
        if: ${{ ! cancelled() }}
        # see https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TESTS_REPORTS_ARTIFACT }}-${{ matrix.os }}-py${{ matrix.python-version }}${{ matrix.toxenv-factors }}
          path: ${{ env.REPORTS_DIR }}
          if-no-files-found: error

      - name: Run Jake on Jake
        run: |
          poetry install --no-dev
          poetry run jake ddt